from __future__ import annotations

from typing import Any

POLICY_UI_OVERRIDES: dict[str, dict[str, Any]] = {
    "AppAutoUpdate": {
        "section": "browser_behavior",
        "subsection": "updates",
        "complexity": "basic",
        "recommended": True,
        "tags": ["updates"],
    },
    "AppUpdateURL": {
        "section": "browser_behavior",
        "subsection": "updates",
        "complexity": "advanced",
        "tags": ["updates"],
    },
    "BackgroundAppUpdate": {
        "section": "browser_behavior",
        "subsection": "updates",
        "complexity": "advanced",
        "tags": ["updates"],
    },
    "BlockAboutConfig": {
        "section": "privacy_security",
        "subsection": "lockdown",
        "complexity": "basic",
        "recommended": True,
        "tags": ["about-pages", "lockdown"],
    },
    "BlockAboutProfiles": {
        "section": "privacy_security",
        "subsection": "lockdown",
        "complexity": "basic",
        "recommended": True,
        "tags": ["about-pages", "lockdown"],
    },
    "DontCheckDefaultBrowser": {
        "section": "browser_behavior",
        "subsection": "startup",
        "complexity": "basic",
        "recommended": True,
        "tags": ["default-browser"],
    },
    "DisableAppUpdate": {
        "section": "browser_behavior",
        "subsection": "updates",
        "complexity": "basic",
        "recommended": True,
        "tags": ["updates"],
    },
    "DisableBuiltinPDFViewer": {
        "section": "privacy_security",
        "subsection": "lockdown",
        "complexity": "advanced",
        "tags": ["pdf", "lockdown"],
    },
    "DisableDeveloperTools": {
        "section": "privacy_security",
        "subsection": "lockdown",
        "complexity": "basic",
        "recommended": True,
        "tags": ["lockdown", "developer-tools"],
    },
    "DisableFirefoxAccounts": {
        "section": "extensions_integrations",
        "subsection": "sync",
        "complexity": "basic",
        "recommended": True,
        "tags": ["sync", "accounts"],
    },
    "DisableFirefoxStudies": {
        "section": "privacy_security",
        "subsection": "data_collection",
        "complexity": "basic",
        "recommended": True,
        "tags": ["telemetry", "studies"],
    },
    "DisableTelemetry": {
        "section": "privacy_security",
        "subsection": "data_collection",
        "complexity": "basic",
        "recommended": True,
        "tags": ["telemetry"],
    },
    "DisablePocket": {
        "section": "home_startup",
        "subsection": "firefox_home",
        "complexity": "basic",
        "tags": ["pocket", "home"],
    },
    "DisablePrivateBrowsing": {
        "section": "privacy_security",
        "subsection": "history",
        "complexity": "basic",
        "recommended": True,
        "tags": ["history", "private-browsing"],
    },
    "DisableSecurityBypass": {
        "section": "privacy_security",
        "subsection": "lockdown",
        "complexity": "advanced",
        "tags": ["security", "lockdown"],
    },
    "DisableSystemAddonUpdate": {
        "section": "browser_behavior",
        "subsection": "updates",
        "complexity": "basic",
        "recommended": True,
        "tags": ["updates"],
    },
    "DNSOverHTTPS": {
        "section": "network_access",
        "subsection": "dns_over_https",
        "complexity": "advanced",
        "recommended": True,
        "tags": ["dns", "network"],
    },
    "ExtensionSettings": {
        "section": "extensions_integrations",
        "subsection": "extensions",
        "complexity": "advanced",
        "recommended": True,
        "tags": ["extensions", "addons"],
    },
    "Extensions": {
        "section": "extensions_integrations",
        "subsection": "extensions_legacy",
        "complexity": "advanced",
        "tags": ["extensions", "addons"],
    },
    "FirefoxHome": {
        "section": "home_startup",
        "subsection": "firefox_home",
        "complexity": "basic",
        "recommended": True,
        "tags": ["home", "new-tab"],
    },
    "FirefoxSuggest": {
        "section": "search",
        "subsection": "suggest",
        "complexity": "basic",
        "recommended": True,
        "tags": ["search", "suggest"],
    },
    "GenerativeAI": {
        "section": "ai_smart",
        "subsection": "availability",
        "complexity": "basic",
        "recommended": True,
        "tags": ["ai", "smart-features"],
    },
    "AIControls": {
        "section": "ai_smart",
        "subsection": "availability",
        "complexity": "basic",
        "recommended": True,
        "tags": ["ai", "smart-features", "feature-controls"],
    },
    "Homepage": {
        "section": "home_startup",
        "subsection": "homepage",
        "complexity": "basic",
        "recommended": True,
        "tags": ["startup", "homepage"],
    },
    "HttpsOnlyMode": {
        "section": "privacy_security",
        "subsection": "https_only",
        "complexity": "basic",
        "recommended": True,
        "tags": ["https-only", "security"],
    },
    "InstallAddonsPermission": {
        "section": "extensions_integrations",
        "subsection": "extensions",
        "complexity": "advanced",
        "tags": ["extensions", "permissions"],
    },
    "ManagedBookmarks": {
        "section": "extensions_integrations",
        "subsection": "bookmarks",
        "complexity": "advanced",
        "tags": ["bookmarks"],
    },
    "Bookmarks": {
        "section": "extensions_integrations",
        "subsection": "bookmarks",
        "complexity": "advanced",
        "tags": ["bookmarks"],
    },
    "NetworkPrediction": {
        "section": "privacy_security",
        "subsection": "network_privacy",
        "complexity": "advanced",
        "tags": ["privacy", "network"],
    },
    "IPProtectionAvailable": {
        "section": "privacy_security",
        "subsection": "network_privacy",
        "complexity": "basic",
        "tags": ["privacy", "network", "vpn"],
    },
    "OfferToSaveLogins": {
        "section": "privacy_security",
        "subsection": "passwords",
        "complexity": "basic",
        "recommended": True,
        "tags": ["passwords"],
    },
    "PasswordManagerEnabled": {
        "section": "privacy_security",
        "subsection": "passwords",
        "complexity": "basic",
        "recommended": True,
        "tags": ["passwords"],
    },
    "Permissions": {
        "section": "privacy_security",
        "subsection": "permissions",
        "complexity": "advanced",
        "tags": ["permissions"],
    },
    "PopupBlocking": {
        "section": "privacy_security",
        "subsection": "permissions",
        "complexity": "advanced",
        "tags": ["popups", "permissions"],
    },
    "Preferences": {
        "section": "advanced",
        "subsection": "preferences",
        "complexity": "advanced",
        "recommended": True,
        "tags": ["preferences"],
    },
    "PromptForDownloadLocation": {
        "section": "browser_behavior",
        "subsection": "downloads",
        "complexity": "basic",
        "recommended": True,
        "tags": ["downloads"],
    },
    "Proxy": {
        "section": "network_access",
        "subsection": "proxy",
        "complexity": "basic",
        "recommended": True,
        "tags": ["proxy", "network"],
    },
    "RequestedLocales": {
        "section": "browser_behavior",
        "subsection": "language",
        "complexity": "advanced",
        "tags": ["language", "localization"],
    },
    "SanitizeOnShutdown": {
        "section": "privacy_security",
        "subsection": "history",
        "complexity": "advanced",
        "recommended": True,
        "tags": ["history", "shutdown"],
    },
    "SearchBar": {
        "section": "search",
        "subsection": "search_ui",
        "complexity": "basic",
        "recommended": True,
        "tags": ["search", "ui"],
    },
    "SearchEngines": {
        "section": "search",
        "subsection": "engines",
        "complexity": "basic",
        "recommended": True,
        "tags": ["search", "engines"],
    },
    "StartDownloadsInTempDirectory": {
        "section": "browser_behavior",
        "subsection": "downloads",
        "complexity": "advanced",
        "tags": ["downloads"],
    },
    "UserMessaging": {
        "section": "home_startup",
        "subsection": "user_messaging",
        "complexity": "advanced",
        "recommended": True,
        "tags": ["messaging", "surfaces"],
    },
    "VisualSearchEnabled": {
        "section": "ai_smart",
        "subsection": "surfaces",
        "complexity": "basic",
        "recommended": True,
        "tags": ["ai", "visual-search", "smart-features"],
    },
    "WebsiteFilter": {
        "section": "extensions_integrations",
        "subsection": "content_filtering",
        "complexity": "advanced",
        "recommended": True,
        "tags": ["filtering", "websites"],
    },
    "WindowsSSO": {
        "section": "network_access",
        "subsection": "authentication",
        "complexity": "advanced",
        "tags": ["authentication", "sso"],
    },
    "Authentication": {
        "section": "network_access",
        "subsection": "authentication",
        "complexity": "advanced",
        "recommended": True,
        "tags": ["authentication", "proxy"],
    },
    "Certificates": {
        "section": "network_access",
        "subsection": "certificates",
        "complexity": "advanced",
        "recommended": True,
        "tags": ["certificates", "tls"],
    },
    "3rdparty": {
        "section": "extensions_integrations",
        "subsection": "third_party",
        "complexity": "advanced",
        "tags": ["extensions", "third-party"],
    },
}
