"""init profiles

Revision ID: 20251022_init_profiles
Revises: None
Create Date: 2025-10-22 00:32:20.122486

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "20251022_init_profiles"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profiles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("schema_version", sa.String(length=50), nullable=False),
        sa.Column("flags", sa.JSON(), nullable=False),
        sa.Column("owner", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_profiles_created_at", "profiles", ["created_at"], unique=False)
    op.create_index("ix_profiles_name", "profiles", ["name"], unique=True)
    op.create_index("ix_profiles_updated_at", "profiles", ["updated_at"], unique=False)
    op.create_index("ix_profiles_schema_version", "profiles", ["schema_version"], unique=False)
    op.create_index("ix_profiles_owner", "profiles", ["owner"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_profiles_owner", table_name="profiles")
    op.drop_index("ix_profiles_schema_version", table_name="profiles")
    op.drop_index("ix_profiles_updated_at", table_name="profiles")
    op.drop_index("ix_profiles_name", table_name="profiles")
    op.drop_index("ix_profiles_created_at", table_name="profiles")
    op.drop_table("profiles")
    # ### end Alembic commands ###
