from __future__ import annotations

from typing import Any

from .builders import bundle_item, chip, doc_target, known_pref, pref_bundle, pref_doc, preset, value_option


def get_privacy_section() -> dict[str, Any]:
    return {
        "id": "privacy",
        "ui_maps": {
            "privacy": [
                chip("data_collection", "profiles.wizard_settings_privacy_data_collection", "Data collection and use"),
                chip("history", "profiles.wizard_settings_privacy_history", "History"),
                chip("passwords", "profiles.wizard_settings_privacy_passwords", "Passwords"),
            ],
            "lockdown": [
                chip("https_only", "profiles.wizard_settings_privacy_https_only", "HTTPS-Only Mode"),
                chip("permissions", "profiles.wizard_settings_privacy_permissions", "Permissions"),
                chip("advanced", "profiles.wizard_settings_advanced_surfaces", "Advanced surfaces"),
            ],
        },
        "ui_docs": {
            "privacy": [
                doc_target("data_collection", "policy:DisableTelemetry", "profiles.policy_disable_telemetry", "Disable telemetry"),
                doc_target("data_collection", "policy:DisableFirefoxStudies", "profiles.policy_disable_studies", "Disable studies"),
                doc_target("history", "policy:DisablePrivateBrowsing", "profiles.policy_disable_private_browsing", "Disable private browsing"),
                doc_target("passwords", "policy:OfferToSaveLogins", "profiles.policy_save_logins", "Offer to save logins"),
                doc_target("passwords", "policy:PasswordManagerEnabled", "profiles.policy_password_manager", "Enable password manager"),
            ],
            "lockdown": [
                doc_target("advanced", "policy:BlockAboutConfig", "profiles.policy_block_about_config", "Block about:config"),
                doc_target("advanced", "policy:BlockAboutProfiles", "profiles.policy_block_about_profiles", "Block about:profiles"),
                doc_target("advanced", "policy:DisableDeveloperTools", "profiles.policy_disable_devtools", "Disable developer tools"),
                doc_target("advanced", "policy:DisableBuiltinPDFViewer", "profiles.policy_disable_pdf_viewer", "Disable built-in PDF viewer"),
                doc_target("https_only", "policy:HttpsOnlyMode", "profiles.policy_https_only", "Enable HTTPS-Only Mode"),
                doc_target("permissions", "pref-section:privacy", "profiles.wizard_preferences_privacy_title", "Managed Preferences for Privacy & Security"),
            ],
        },
        "preferences": {
            "id": "privacy",
            "title_key": "profiles.wizard_preferences_privacy_title",
            "body_key": "profiles.wizard_preferences_privacy_body",
            "gui_groups": [
                chip("tracking", "profiles.wizard_preferences_group_privacy_tracking", "Enhanced Tracking Protection"),
                chip("passwords", "profiles.wizard_preferences_group_privacy_passwords", "Passwords"),
                chip("autofill", "profiles.wizard_preferences_group_privacy_autofill", "Forms and autofill"),
                chip("permissions", "profiles.wizard_preferences_group_privacy_permissions", "Permissions"),
                chip("https_only", "profiles.wizard_preferences_group_privacy_https_only", "HTTPS-Only Mode"),
                chip("dns_over_https", "profiles.wizard_preferences_group_privacy_dns_over_https", "DNS over HTTPS"),
                chip("security", "profiles.wizard_preferences_group_privacy_security", "Security"),
            ],
            "docs": [
                pref_doc("tracking", "privacy_tracking", "profiles.wizard_preferences_preset_privacy_tracking_title", "Strict tracking protection"),
                pref_doc("tracking", "privacy_dnt", "profiles.wizard_preferences_preset_privacy_dnt_title", "Send Do Not Track"),
                pref_doc("passwords", "privacy_passwords", "profiles.wizard_preferences_preset_privacy_passwords_title", "Disable password saving"),
                pref_doc("autofill", "privacy_forms", "profiles.wizard_preferences_preset_privacy_forms_title", "Disable form autofill"),
                pref_doc("https_only", "privacy_https_only", "profiles.wizard_preferences_preset_privacy_https_only_title", "Enable HTTPS-Only Mode"),
                pref_doc("dns_over_https", "privacy_doh_default", "profiles.wizard_preferences_preset_privacy_doh_default_title", "Enable DNS over HTTPS"),
                pref_doc("permissions", "privacy_geo_block", "profiles.wizard_preferences_preset_privacy_geo_block_title", "Block location requests"),
                pref_doc("permissions", "privacy_camera_block", "profiles.wizard_preferences_preset_privacy_camera_block_title", "Block camera requests"),
                pref_doc("permissions", "privacy_microphone_block", "profiles.wizard_preferences_preset_privacy_microphone_block_title", "Block microphone requests"),
            ],
            "prefixes": [
                "browser.contentblocking.",
                "browser.formfill.",
                "browser.safebrowsing.",
                "datareporting.policy.",
                "dom.security.https_only_mode",
                "geo.",
                "network.cookie.",
                "network.trr.",
                "permissions.default.",
                "pdfjs.",
                "privacy.",
                "security.",
                "signon.",
            ],
            "presets": [
                preset("privacy_tracking", "browser.contentblocking.category", "strict", "locked", "string", "profiles.wizard_preferences_preset_privacy_tracking_title", "profiles.wizard_preferences_preset_privacy_tracking_copy"),
                preset("privacy_dnt", "privacy.donottrackheader.enabled", True, "default", "boolean", "profiles.wizard_preferences_preset_privacy_dnt_title", "profiles.wizard_preferences_preset_privacy_dnt_copy"),
                preset("privacy_passwords", "signon.rememberSignons", False, "locked", "boolean", "profiles.wizard_preferences_preset_privacy_passwords_title", "profiles.wizard_preferences_preset_privacy_passwords_copy"),
                preset("privacy_forms", "browser.formfill.enable", False, "locked", "boolean", "profiles.wizard_preferences_preset_privacy_forms_title", "profiles.wizard_preferences_preset_privacy_forms_copy"),
                preset("privacy_https_only", "dom.security.https_only_mode", True, "locked", "boolean", "profiles.wizard_preferences_preset_privacy_https_only_title", "profiles.wizard_preferences_preset_privacy_https_only_copy"),
                preset("privacy_doh_default", "network.trr.mode", 2, "locked", "number", "profiles.wizard_preferences_preset_privacy_doh_default_title", "profiles.wizard_preferences_preset_privacy_doh_default_copy"),
                preset("privacy_geo_block", "permissions.default.geo", 2, "locked", "number", "profiles.wizard_preferences_preset_privacy_geo_block_title", "profiles.wizard_preferences_preset_privacy_geo_block_copy"),
                preset("privacy_camera_block", "permissions.default.camera", 2, "locked", "number", "profiles.wizard_preferences_preset_privacy_camera_block_title", "profiles.wizard_preferences_preset_privacy_camera_block_copy"),
                preset("privacy_microphone_block", "permissions.default.microphone", 2, "locked", "number", "profiles.wizard_preferences_preset_privacy_microphone_block_title", "profiles.wizard_preferences_preset_privacy_microphone_block_copy"),
            ],
            "bundles": [
                pref_bundle(
                    "privacy_site_permissions_lockdown",
                    "permissions",
                    "profiles.wizard_preferences_bundle_permissions_title",
                    "profiles.wizard_preferences_bundle_permissions_copy",
                    [
                        bundle_item("permissions.default.geo", 2, "locked", "number"),
                        bundle_item("permissions.default.camera", 2, "locked", "number"),
                        bundle_item("permissions.default.microphone", 2, "locked", "number"),
                        bundle_item("permissions.default.desktop-notification", 2, "locked", "number"),
                    ],
                ),
                pref_bundle(
                    "privacy_doh_hardened",
                    "dns_over_https",
                    "profiles.wizard_preferences_bundle_doh_title",
                    "profiles.wizard_preferences_bundle_doh_copy",
                    [
                        bundle_item("network.trr.mode", 3, "locked", "number"),
                        bundle_item("security.enterprise_roots.enabled", True, "default", "boolean"),
                    ],
                ),
            ],
            "known_preferences": [
                known_pref(
                    "browser.contentblocking.category",
                    "Tracking protection mode",
                    "Selects the main Enhanced Tracking Protection posture Firefox presents to users.",
                    value_type="string",
                    status="locked",
                    value_control="select",
                    value_options=[
                        value_option("standard", "Standard"),
                        value_option("strict", "Strict"),
                        value_option("custom", "Custom"),
                    ],
                ),
                known_pref(
                    "network.cookie.cookieBehavior",
                    "Cookie policy",
                    "Controls how aggressively Firefox blocks third-party and tracking cookies.",
                    value_type="number",
                    status="default",
                    value_control="select",
                    value_options=[
                        value_option(0, "Allow all cookies"),
                        value_option(1, "Block third-party cookies"),
                        value_option(4, "Block cross-site tracking cookies"),
                        value_option(5, "Total Cookie Protection"),
                    ],
                ),
                known_pref(
                    "network.trr.mode",
                    "DNS over HTTPS mode",
                    "Chooses how strongly Firefox prefers or requires DNS over HTTPS resolvers.",
                    value_type="number",
                    status="locked",
                    value_control="select",
                    value_options=[
                        value_option(0, "Off"),
                        value_option(2, "TRR first"),
                        value_option(3, "TRR only"),
                        value_option(5, "Off by choice"),
                    ],
                ),
                known_pref(
                    "permissions.default.geo",
                    "Location permission default",
                    "Sets the default behavior for new geolocation permission requests.",
                    value_type="number",
                    status="locked",
                    value_control="select",
                    value_options=[
                        value_option(0, "Always ask"),
                        value_option(1, "Allow by default"),
                        value_option(2, "Block by default"),
                    ],
                ),
                known_pref(
                    "permissions.default.camera",
                    "Camera permission default",
                    "Sets the default behavior for new camera permission prompts.",
                    value_type="number",
                    status="locked",
                    value_control="select",
                    value_options=[
                        value_option(0, "Always ask"),
                        value_option(1, "Allow by default"),
                        value_option(2, "Block by default"),
                    ],
                ),
                known_pref(
                    "permissions.default.microphone",
                    "Microphone permission default",
                    "Sets the default behavior for new microphone permission prompts.",
                    value_type="number",
                    status="locked",
                    value_control="select",
                    value_options=[
                        value_option(0, "Always ask"),
                        value_option(1, "Allow by default"),
                        value_option(2, "Block by default"),
                    ],
                ),
                known_pref(
                    "permissions.default.desktop-notification",
                    "Notification permission default",
                    "Sets the default behavior for sites that want to send desktop notifications.",
                    value_type="number",
                    status="locked",
                    value_control="select",
                    value_options=[
                        value_option(0, "Always ask"),
                        value_option(1, "Allow by default"),
                        value_option(2, "Block by default"),
                    ],
                ),
                known_pref(
                    "privacy.clearOnShutdown.history",
                    "Clear history on shutdown",
                    "Removes browsing history whenever Firefox closes.",
                    value_type="boolean",
                    status="default",
                ),
                known_pref(
                    "privacy.clearOnShutdown.cookies",
                    "Clear cookies on shutdown",
                    "Deletes site cookies when Firefox exits.",
                    value_type="boolean",
                    status="default",
                ),
                known_pref(
                    "privacy.resistFingerprinting",
                    "Resist fingerprinting",
                    "Enables Firefox anti-fingerprinting protections.",
                    value_type="boolean",
                    status="default",
                ),
                known_pref(
                    "security.enterprise_roots.enabled",
                    "Trust enterprise roots",
                    "Lets Firefox trust certificates from the operating system trust store.",
                    value_type="boolean",
                    status="default",
                ),
            ],
        },
    }
