#!/usr/bin/env python3
"""Generate the compact BPM documentation subsystem snapshot."""

from __future__ import annotations

import hashlib
from pathlib import Path

REPOSITORY_ROOT = Path(__file__).resolve().parents[2]
DOCUMENTATION_ROOT = REPOSITORY_ROOT / "documentation"
OUTPUT_PATH = DOCUMENTATION_ROOT / "PROJECT_SNAPSHOT.generated.md"
TARGET_VERSION = "0.9.0"
EXCLUDED_PARTS = {
    ".cache",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".toolchain",
    ".venv",
    "__pycache__",
    "build",
    "dist",
    "html",
    "node_modules",
    "reports",
    "vendor",
}
EXCLUDED_SUFFIXES = {".gif", ".ico", ".jpg", ".jpeg", ".png", ".pyc", ".tar", ".tgz", ".xz", ".zip"}
APP_DOCUMENTATION_ROOT = REPOSITORY_ROOT / "app/documentation"
ARCHITECTURE_ENTRY_POINTS = (
    "product-documentation-ownership-boundary-0.9.0.md",
    "dita-publishing-toolchain-decision-0.9.0.md",
    "documentation-identifiers-and-url-conventions-0.9.0.md",
    "product-documentation-manifest-and-ui-target-schema-0.9.0.md",
    "product-documentation-provenance-review-0.9.0.md",
    "product-documentation-accessibility-security-contract-0.9.0.md",
    "product-documentation-release-contract-0.9.0.md",
    "product-user-capability-inventory-0.9.0.md",
    "firefox-policy-documentation-inventory-0.9.0.json",
    "cis-documentation-inventory-0.9.0.json",
    "api-documentation-inventory-0.9.0.md",
)
DOCUMENTATION_COMMANDS = (
    "make setup-docs-toolchain",
    "make setup-docs-toolchain DOCS_TOOLCHAIN_OFFLINE=1",
    "make docs-snapshot",
    "make docs-fast-check DOCS_CHANGED=\"documentation/src/dita/en/user/example.dita\"",
    "make docs-coverage",
    "make docs-release-check",
    "make test-docs",
    "make test-docs-contract",
    "make test-docs-ui-contract",
    "make test-docs-browser",
    "make test-docs-ui",
    "make docs-validate",
    "make docs-build",
    "make docs-reproducibility-check",
    "make docs-package",
    "make docs-package-verify",
)


def _included(path: Path) -> bool:
    relative = path.relative_to(REPOSITORY_ROOT)
    if any(part in EXCLUDED_PARTS for part in relative.parts):
        return False
    return path.suffix.lower() not in EXCLUDED_SUFFIXES


def _files_under(root: Path) -> list[Path]:
    if not root.exists():
        return []
    return sorted(path for path in root.rglob("*") if path.is_file() and _included(path))


def _repo_path(path: Path) -> str:
    return path.relative_to(REPOSITORY_ROOT).as_posix()


def _digest(paths: list[Path]) -> str:
    hasher = hashlib.sha256()
    for path in sorted(paths):
        hasher.update(_repo_path(path).encode())
        hasher.update(b"\0")
        hasher.update(hashlib.sha256(path.read_bytes()).digest())
    return hasher.hexdigest()


def _topic_counts() -> dict[str, int]:
    counts: dict[str, int] = {}
    for locale_root in sorted((DOCUMENTATION_ROOT / "src/dita").glob("*")):
        if locale_root.is_dir():
            counts[locale_root.name] = len(sorted(locale_root.rglob("*.dita")))
    return counts


def _line(label: str, paths: list[Path]) -> str:
    return f"- {label}: {len(paths)} files, sha256 `{_digest(paths)[:16]}`"


def generate_snapshot() -> str:
    source_paths = [
        *_files_under(DOCUMENTATION_ROOT / "src/dita"),
        *_files_under(DOCUMENTATION_ROOT / "src/shared"),
        *_files_under(DOCUMENTATION_ROOT / "src/generated"),
        *_files_under(DOCUMENTATION_ROOT / "assets/theme"),
    ]
    config_paths = _files_under(DOCUMENTATION_ROOT / "config")
    fixture_paths = _files_under(DOCUMENTATION_ROOT / "fixtures")
    runbook_paths = _files_under(DOCUMENTATION_ROOT / "runbooks")
    tool_paths = _files_under(DOCUMENTATION_ROOT / "tools")
    test_paths = _files_under(DOCUMENTATION_ROOT / "tests")
    runtime_paths = _files_under(APP_DOCUMENTATION_ROOT)
    architecture_paths = [
        REPOSITORY_ROOT / "docs/architecture" / name
        for name in ARCHITECTURE_ENTRY_POINTS
        if (REPOSITORY_ROOT / "docs/architecture" / name).is_file()
    ]
    all_paths = [
        *source_paths,
        *config_paths,
        *fixture_paths,
        *runbook_paths,
        *tool_paths,
        *test_paths,
        *runtime_paths,
        *architecture_paths,
    ]
    topic_counts = _topic_counts()
    lines = [
        "# BPM Documentation Subsystem Snapshot",
        "",
        "Generated by `documentation/tools/generate_subsystem_snapshot.py`.",
        f"Target BPM version: `{TARGET_VERSION}`",
        f"Deterministic input digest: `{_digest(all_paths)}`",
        "",
        "## Bounded Surface",
        "",
        _line("DITA/shared/generated sources and theme assets", source_paths),
        _line("Configuration and policy contracts", config_paths),
        _line("Compact fixtures", fixture_paths),
        _line("Maintainer runbooks", runbook_paths),
        _line("Documentation tools", tool_paths),
        _line("Documentation tests", test_paths),
        _line("Runtime `/help/` bridge", runtime_paths),
        _line("Architecture entry points", architecture_paths),
        "",
        "## Locale Topic Counts",
        "",
        *[f"- `{locale}`: {count} DITA topics" for locale, count in sorted(topic_counts.items())],
        "",
        "## Commands",
        "",
        *[f"- `{command}`" for command in DOCUMENTATION_COMMANDS],
        "",
        "## Excluded By Design",
        "",
        "- disposable build, distribution, reports, cache, and toolchain directories",
        "- generated pages, generated search indexes, coverage reports, diagnostics, caches, pyc files, dependency folders, and screenshot binaries",
        "- unrelated application modules outside the documentation runtime bridge",
        "",
        "## Entry Points",
        "",
        "- `documentation/PROJECT_SNAPSHOT.md`",
        "- `documentation/AGENTS.md`",
        "- `documentation/tests/suite-boundaries-0.9.0.json`",
        "- `documentation/fixtures/fixture-catalog-0.9.0.json`",
        "- `documentation/config/diagnostics-policy-0.9.0.json`",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    OUTPUT_PATH.write_text(generate_snapshot(), encoding="utf-8")
    print(f"Generated {OUTPUT_PATH.relative_to(REPOSITORY_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
