#!/usr/bin/env python3
from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
LAYER_DIR = REPO_ROOT / "app" / "static" / "profiles_css"
BUNDLE_PATH = REPO_ROOT / "app" / "static" / "profiles.css"
LAYERS = (
    "00-foundation.css",
    "10-library.css",
    "20-editor-wizard.css",
    "30-responsive.css",
    "40-compact-shell.css",
)
HEADER = """/* Generated by tools/build_profiles_css.py.
   Edit app/static/profiles_css/*.css, then run `make build-profiles-css`. */
"""


def build_css() -> str:
    sections = [HEADER.rstrip()]
    for layer_name in LAYERS:
        layer_path = LAYER_DIR / layer_name
        sections.append(f"/* profiles_css/{layer_name} */")
        sections.append(layer_path.read_text(encoding="utf-8").rstrip())
    return "\n\n".join(sections) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Build the /profiles CSS bundle.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero when app/static/profiles.css is not generated from the layer files.",
    )
    args = parser.parse_args()

    next_css = build_css()
    if args.check:
        current_css = BUNDLE_PATH.read_text(encoding="utf-8")
        if current_css != next_css:
            print(
                "app/static/profiles.css is out of date; run `make build-profiles-css`.",
                file=sys.stderr,
            )
            return 1
        return 0

    BUNDLE_PATH.write_text(next_css, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
