from __future__ import annotations


def get_wizard_steps() -> list[dict[str, object]]:
    """Return the ordered task-first steps for the main wizard flow."""

    return [
        {
            "id": "browser_network_search",
            "step": 1,
            "label_key": "profiles.wizard_step_one",
            "label_fallback": "Browser, network & search",
            "copy_key": "profiles.wizard_step_one_copy",
            "copy_fallback": "Browser behavior, network access, and search defaults.",
            "progress_key": "profiles.wizard_progress_one",
            "progress_fallback": "Step 1 of 8: Browser, network & search",
        },
        {
            "id": "urls_sites_navigation",
            "step": 2,
            "label_key": "profiles.wizard_step_two",
            "label_fallback": "URLs, sites & navigation",
            "copy_key": "profiles.wizard_step_two_copy",
            "copy_fallback": "Home pages, navigation, and managed site access.",
            "progress_key": "profiles.wizard_progress_two",
            "progress_fallback": "Step 2 of 8: URLs, sites & navigation",
        },
        {
            "id": "security_privacy",
            "step": 3,
            "label_key": "profiles.wizard_step_three",
            "label_fallback": "Security & privacy",
            "copy_key": "profiles.wizard_step_three_copy",
            "copy_fallback": "Privacy controls, permissions, cookies, cleanup, and hardening posture.",
            "progress_key": "profiles.wizard_progress_three",
            "progress_fallback": "Step 3 of 8: Security & privacy",
        },
        {
            "id": "certificates_trust",
            "step": 4,
            "label_key": "profiles.wizard_step_four",
            "label_fallback": "Certificates & trust",
            "copy_key": "profiles.wizard_step_four_copy",
            "copy_fallback": "Trusted certificates, security devices, and certificate policy.",
            "progress_key": "profiles.wizard_progress_four",
            "progress_fallback": "Step 4 of 8: Certificates & trust",
        },
        {
            "id": "users_language_sync",
            "step": 5,
            "label_key": "profiles.wizard_step_five",
            "label_fallback": "Users, language & sync",
            "copy_key": "profiles.wizard_step_five_copy",
            "copy_fallback": "Accounts, language, translation, and sync.",
            "progress_key": "profiles.wizard_progress_five",
            "progress_fallback": "Step 5 of 8: Users, language & sync",
        },
        {
            "id": "extensions",
            "step": 6,
            "label_key": "profiles.wizard_step_six",
            "label_fallback": "Extensions",
            "copy_key": "profiles.wizard_step_six_copy",
            "copy_fallback": "Allowed, blocked, required, and managed extensions.",
            "progress_key": "profiles.wizard_progress_six",
            "progress_fallback": "Step 6 of 8: Extensions",
        },
        {
            "id": "ai",
            "step": 7,
            "label_key": "profiles.wizard_step_seven",
            "label_fallback": "AI",
            "copy_key": "profiles.wizard_step_seven_copy",
            "copy_fallback": "Built-in AI, visual search, and smart browser features.",
            "progress_key": "profiles.wizard_progress_seven",
            "progress_fallback": "Step 7 of 8: AI",
        },
        {
            "id": "review_export",
            "step": 8,
            "label_key": "profiles.wizard_step_eight",
            "label_fallback": "Review & export",
            "copy_key": "profiles.wizard_step_eight_copy",
            "copy_fallback": "Check settings, save, and download policy files.",
            "progress_key": "profiles.wizard_progress_eight",
            "progress_fallback": "Step 8 of 8: Review & export",
        },
    ]
